version: "3.9"
services:
  # === Postgres DB === #
  db:
    image: postgres:latest
    container_name: autometrics_demo_db
    environment:
      POSTGRES_PASSWORD: autometrics
      POSTGRES_USER: autometrics
      POSTGRES_DB: autometrics_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # === Main Node.js API === #
  api:
    build: ./api
    ports:
      - "${FP_API_PORT:-8081}:8080"
    environment:
      POSTGRES_PASSWORD: autometrics
      POSTGRES_USER: autometrics
      POSTGRES_DB: autometrics_demo
    env_file:
      - ./.env
    volumes:
      - ./api/public:/app/public
  
  embeddings:
    build: ./embeddings
    ports:
      - "${FP_EMBEDDINGS_PORT:-8082}:5000"
    env_file:
      - ./.env

volumes:
  postgres_data:
