version: "3.9"
services:
  # === Postgres DB with vector extension === #
  db:
    # image: ankane/pgvector
    build: ./db
    environment:
      POSTGRES_PASSWORD: autometrics
      POSTGRES_USER: autometrics
      POSTGRES_DB: autometrics_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === Main Node.js API === #
  api:
    build: ./api
    mem_limit: 512m
    ports:
      - "${FP_API_PORT:-8081}:8080"
      - "9464:9464"
    environment:
      POSTGRES_PASSWORD: autometrics
      POSTGRES_USER: autometrics
      POSTGRES_DB: autometrics_demo
    env_file:
      - ./.env
    volumes:
      - ./api/public:/app/public

  # === Python embeddings service === #
  embeddings:
    build: ./embeddings
    mem_limit: 1g
    ports:
      - "${FP_EMBEDDINGS_PORT:-8082}:5000"
    environment:
      AUTOMETRICS_VERSION: 0.0.1
      AUTOMETRICS_TRACKER: prometheus 
    env_file:
      - ./.env

volumes:
  postgres_data:
